0913 정수론
Altu-Bitu-3/Altu-Bitu-KimMinSeo pull request #5
Opened 2022-09-18 17:18 UTC by seoyamin

#### 내용 & 질문
> 제출합니다!

#### <기존 제출>
> 1213, 2108, 2168, 9421, 14490

2022-09-18 17:21 UTC, seoyamin commented
6588번, 20302번은 미해결 문제이지만 피드백을 부탁드리고 싶어서 같이 커밋했습니다 :)

6588번은 시간 초과 문제가, 20302번은 출력은 동일한데 틀렸다고 나와서 어떤 부분이 부족했는지 궁금합니다!

2022-09-18 19:38 UTC, dooli1971039 reviewed
**p2. 1213 코드 리뷰 완료**
안녕하세요 민서님~
문제 푸시느라 정말 고생 많으셨어요!!👍👍
풀이에 대해 약간의 코멘트 남겼습니다!
궁금한 점 있으시면 리뷰어를 호출해주세요~
수고하셨습니다!!

2022-09-18 19:38 UTC, dooli1971039 commented on 09월 13일 - 정수론/1213.cpp
> +
p2. 알파벳과 등장횟수를 저장하시기 위해 map을 사용하셨군요.
`int alpha[26];` 이런식으로 알파벳 배열을 선언하고, 등장횟수를 저장하는 방법도 있습니다. 참고해주세요😊

2022-09-19 04:00 UTC, dbswn approved these changes
**P2 9421 코드리뷰 완료**
안녕하세요 민서님 !! 😊주석도, 문제풀이도 너무 깔끔해서 코드 읽기 너무 좋았습니다👍 함수화도 잘 해주셨고 각 자릿수의 제곱의 합을 구하는 방법이 참신해서 너무 좋았습니다! 본 코드를 그대로 샘플코드로 제공해드려도 될 정도에요~! 코드 구경 잘 하고 갑니다😄

간단한 코멘트 달았으니, 확인 부탁 드립니다 !수정하신 부분 있으시면 리뷰어로 불러주셔도 좋습니다! 수고 많으셨습니다.감사합니다. 🤗🤗

2022-09-19 04:00 UTC, dbswn commented on 09월 13일 - 정수론/9421.cpp
> +			result += (s[i] - '0') * (s[i] - '0');
P2
각 자리 수의 제곱의 합을 구하는 부분이 반복되고 있는데 함수화를 해보는게 어떨까요? 함수로 뺄 수 있는 것은 최대한 빼주는 것이 후에 코드를 보수하고 재사용하기에 좋답니다!😊

2022-09-19 08:51 UTC, bsa0322 requested changes
**p1. 14490 코드리뷰 완료**
민서님 안녕하세요 ❤ 함수화도 잘해주시고 코드 깔끔하게 너무 잘짜주셔서 잘 읽혔네요!! 문자열 분리하는 부분에 대해 해결할 수 있는 다른 풀이 제시했으니 확인해주시면 좋을 것 같습니다.

p1 코멘트는 꼭 수정 후, 저 다시 리뷰어로 호출해주세요!! 수고하셨습니다 💘

2022-09-19 08:51 UTC, bsa0322 commented on 09월 13일 - 정수론/14490.cpp
> +}
p1. 최대공약수를 O(n)으로 찾아주셨네요!! 튜터링에서 더욱 효율적으로 최대공약수를 찾을 수 있는 방법에 대해 다뤘으니 강의 참고 부탁드려요 💘🔥

2022-09-19 08:51 UTC, bsa0322 commented on 09월 13일 - 정수론/14490.cpp
> +	}
정답 찾는 부분 함수화해주신 거 아주 좋습니다!! ❤

p2. 문자열 분리를 반복문으로 직접 구현해주셨네요! check변수로 관리해서 두 개 문자 분리해주신 방법 너무너무 좋아요!!!!!! 다만, 코테에서는 시간이 없으니 코드를 간결하게 짤 수 있는 라이브러리 함수를 많이 활용하면 좋을 것 같아요~! 

문자열을 찾는 기능을 활용해서 ':' 를 찾은 다음에, 분리하면 어떨까요? 문자열을 분리하는 함수 `substr`에 대해서 알아보시면 좋을 것 같아요~!

아니면 getline을 활용해서 아예 입력 시에 두 수를 분리해서 받을 수 있을 것 같습니다 😎😎 저희 샘플코드 참고해주셔도 좋을 것 같아요!!!

2022-09-19 14:05 UTC, grdnr13 reviewed
**p2. 2108번 코드리뷰 완료**
안녕하세요, 민서님! 코드 효율성 관련해서 코멘트 남겼으니 참고부탁드립니다.
문제 푸느라 고생하셨어요!
궁금한 게 생기시면 리뷰어로 호출해주세요😃😃

2022-09-19 14:05 UTC, grdnr13 commented on 09월 13일 - 정수론/2108.cpp
> +	}
p2. 입력값들의 합은 main함수에서 값을 입력받을 때 한번에 해결이 가능해요! 이렇게 하면 불필요한 반복을 줄일 수 있습니다😀

2022-09-19 14:05 UTC, grdnr13 commented on 09월 13일 - 정수론/2108.cpp
> +	int avg = 0;
p3. `avg`를 `double`로 선언하면, 뒤에서 형변환을 거칠 필요가 없어져요! 
(자료형을 섞어서 연산을 하면 컴파일러에서 암시적 형 변환을 해줍니다)

2022-09-19 14:05 UTC, grdnr13 commented on 09월 13일 - 정수론/2108.cpp
> +	avg = floor((double)avg/v.size() + 0.5);  // 반올림
p3. 반올림 잘 구현해주셨네요😎
C++11 이상 버전에서는 `<cmath>`의 `round()`메서드로 반올림 연산이 가능합니다! 참고해주세요~

2022-09-19 14:05 UTC, grdnr13 commented on 09월 13일 - 정수론/2108.cpp
> +	else med = v[v.size() / 2];
p2. 문제 조건에서 N이 홀수라고 주어졌으므로, 두 케이스를 나눌 필요는 없습니다~
꼼꼼하게 케이스 나눠서 생각해보는건 좋은 습관이에요!!👍👍

2022-09-19 14:05 UTC, grdnr13 commented on 09월 13일 - 정수론/2108.cpp
> +bool cmp(pair<int, int>& a, pair<int, int>& b) {
p3. `pair<int,int>`처럼 자주 사용하는 타입은 `typedef`를 통해 별칭을 정하는게 좋아요

2022-09-19 14:05 UTC, grdnr13 commented on 09월 13일 - 정수론/2108.cpp
> +	sort(v.begin(), v.end(), cmp);
p2. map 대신에 처음부터 vector를 이용하는 방법도 있으니, 참고해주세요!

2022-09-19 14:32 UTC, 0321minji commented
**2168 코드리뷰 완료**
안녕하세요 민서님!
이번 문제가 풀이 방법을 생각하기까지가 어려운 문제였는데 잘 풀이해주셨네요👍👍
gcd 함수 구현과 관련해서 코멘트 드렸으니 확인부탁드립니다😊😊
p1 코멘트 수정 후에 리뷰어로 호출 부탁드려요😉😉 수고하셨습니다!!

2022-09-19 14:35 UTC, 0321minji requested changes

2022-09-19 14:35 UTC, 0321minji commented on 09월 13일 - 정수론/2168.cpp
> +}
p1. 
gcd 함수를 반복문을 통해 구현(O(n))해주셨는데, 이를 재귀와 나머지 연산을 이용하여 더 깔끔하게 구현할 수 있을 것 같아 보여요! 튜터링 강의 참고해주시면 좋을 것 같아요! 혹시 질문 있으시다면 편하게 남겨주세요!!

2022-09-19 15:47 UTC, seoyamin commented on 09월 13일 - 정수론/14490.cpp
> +}
허걱 저한테 익숙한 gcd 함수만 쓰다 보니 시간 복잡도를 놓쳤었네요...!! 
재귀함수 방식으로 수정 후 푸쉬했습니다! 리뷰 감사드립니다🥰

2022-09-19 16:00 UTC, seoyamin commented on 09월 13일 - 정수론/2168.cpp
> +}
강의에서 배웠던 유클리드 호제법 방식으로 수정해봤습니다 :D 
리뷰 감사합니다🥰

2022-09-19 16:02 UTC, seoyamin commented on 09월 13일 - 정수론/14490.cpp
> +}
익숙한 함수만 쓰려다 보니 시간복잡도를 놓쳤었네요..!
유클리드 호제법을 이용해서 gcd 구하는 함수로 수정했습니다ㅎㅎ
리뷰 감사드려요! 🥰

2022-09-21 10:13 UTC, 0321minji commented on 09월 13일 - 정수론/2168.cpp
> +}
p2.
result에 값을 대입하는 식에서 괄호를 제거해볼까요? 
사소하지만 조금 다른 풀이기에 샘플코드 풀이도 참고해보시면 좋을 것 같아요!!

2022-09-25 02:56 UTC, merged